{% set name = "mpg123" %}
{% set version = "1.25.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.bz2/download
  sha256: 79da51efae011814491f07c95cb5e46de0476aca7a0bf240ba61cfc27af8499b

build:
    number: 1000
    skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f $PREFIX/lib/libmpg123${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/libout123${SHLIB_EXT}  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [linux]

about:
    home: https://www.mpg123.de/
    license: LGPL-2.1
    license_family: LGPL
    license_file: COPYING
    summary: "mpg123 - fast console MPEG Audio Player and decoder library"
    dev_url: https://www.mpg123.de/index.shtml
    doc_url: https://www.mpg123.de/api/

extra:
    recipe-maintainers:
        - hbredin
        - thomasfillon
