travis:
  secure:
    BINSTAR_TOKEN: mV1A4FWlnKVL8FMxdwSwMjeIt6hvb2iM55Eo7Tv+qsskC8md+OGSH+SmwkTuXfIHCtQtd1Fw8hsz7MKEFoT0gHFCqKYF6gI7F0I6XGuo0oBhzLmblSXz9/+GapQdTPFrWP7V5/2b5g1mZOVd76eVfIHuZIqtxF1lMsGZAhSqTj766YTf7poPDB9Y+b2ysLm7PnxvyToAw0+xI8xHnCYaB5Ep/FsFo0kulskPrjpUY5HCJ+0dDnlCtAbLQQiIKhz6/9UiIZJcONdmWfYz9a+AkZy0+RFg/1K4NqigvL96ZMo5NDgDTHrJzcYQJrXMsbQYYZ362I9R21A0x5BZmdylfdg8C7vWUDqoBLBv03L11vITba8D96/EEytTqMYB75FvFvO4I5Q4jmFUjtThBQhoU7VbBXzI1WLHkNJjnt0b1aehseP0LGWBlQAr9ZD4I3l5C9btFC3ercrGjTxiMp6YV063TvEkpXVVrzmmiohBomQewhAotJvju7kL0bf+QaPbzBH8M/ic/IKbiEcW5EUpXXwljbw7kSotX8VebkyBvMm+BqnfU1XQMJZjSeAThe/ldH2gl5etteINjFZh3wGcL8y0tPIIkeSIDfeZhnlx/HOSb3onPgjaUVamvo+cVwvwVaJIvNgofdymUQFV/Ezee4m7e9GgG9ljIB4HoVGj8yw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
