travis:
  secure:
    BINSTAR_TOKEN: A9BUuOxKf7oZE+p2ZZQsooZN4khRWdPQ/IDY3xKr0pQi+9SrBNQzk2LDjDwHewVIdbdoXvWCxkYAUI65lsmLxy/I2tmvusgP00MUjjTPbyvsm0zgjZk4QC6wdGyKVfsObwRPMBxSl1Do6Vp6aZdrPyISiifPgMBdwSavKXtyzCrqdc7bDTBrk3I4abpDZwhcywH0NE0nW7mwmqEaCkGjjAFwP4MlzYnGN+SnHnIxfWLycVLnpZKXZuL3umqL+FxgqYpBDzwFfg73VKWIY++OS76Ghe+KF4c64b2BFkQNRYjzABfpRxDihnVtZcf6boZvzmkXbCVNmNIDgxWgun0dN5aLfwOHm8HctWUiIk7Z6HiZfgB8uLaBIGl9eZywj64SDDk3iZVEOI9KFfHtub4ndiZ5BwhxP3mNE+BD2EAMZvvSaB1R5XW72ldDfOQQYC8MfdRKL/qiLDWqTWKFswSyUg9hMvaRmszoJA5WzwJIwd8Bb9srJ0ehG1RGI7o0CxsFv1xN/z1OMpU5J5peGKRSPymwV5Esn5PQ2IsJcmTdA30Q4n9yEWvTZysbIt+I1Eajom1gwXaOr9o6zWKi+d2q78rVEh3na/P3RvigZSoTSkCGAHaZcAcRpJnPRZwPGCbDOkJ5e3qtjb2ge00KwuyqTphrHTSUvFxIQlNRqK+FIZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
